AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Amazon API Gateway REST API with Cognito User Pools Authorizer

Globals:
  Function:
    Runtime: nodejs14.x
    CodeUri: src/

Parameters:
  CognitoUserPoolArn:
    Description: arn:aws:cognito-idp:us-east-2:335004744309:userpool/us-east-2_C2BybC3Ty
    Type: String

Resources:
  # REST API
  AppApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: cognito-restapi
      Description: Cognito User Pools Authorizer REST API demo

  RootMethodGet:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref AppApi
      ResourceId: !GetAtt AppApi.RootResourceId
      HttpMethod: GET
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref AuthorizersCognitoUserPools
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Join [ '', [ 'arn:aws:apigateway:', !Ref AWS::Region, ':lambda:path/2015-03-31/functions/', !GetAtt AppFunction.Arn, '/invocations' ] ]

  AuthorizersCognitoUserPools:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: CognitoAuthorizer
      Type: COGNITO_USER_POOLS
      RestApiId: !Ref AppApi
      IdentitySource: method.request.header.authorizationToken
      ProviderARNs:
        - !Ref arn:aws:cognito-idp:us-east-2:335004744309:userpool/us-east-2_C2BybC3Ty

  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler

  AppFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AppFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${AppApi}/*/GET/

  Deployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - RootMethodGet
    Properties:
      RestApiId: !Ref AppApi
  
  Stage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: Prod
      RestApiId: !Ref AppApi
      DeploymentId: !Ref Deployment

Outputs:

  AppApiEndpoint:
    Description: API Endpoint
    Value: !Sub "https://${AppApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"